### PR TITLE
ChainerCV testcases + Subscript Assignments (1/2)

### PR DESCRIPTION
**Pull request by Rishav1**
PR includes chainercv pfn models and fixes to elichika for sucessfully compiling these models.

### CODE REVIEW

**Comment by Rishav1** [comment]
Sorry I haven't been able to address travis failures yet. Been busy with assignments 😅. Will fix the tests this weekend.

**Comment by shinh** [comment]
Looks like this is ready to be merged? OK to remove WIP?

**Comment by Rishav1** [comment]
Not yet. The PFN test doesn't pass yet. I have to implement a solution to [assignment bug in list/tensor](https://github.com/pfnet-research/chainer-compiler/blob/master/testcases%2Felichika_tests%2Fsyntax%2FList.py/#L69) for passing the FPN test I added. Will do it by this weekend.

**Comment by Rishav1** [comment]
Failure is due to update in pypi `gast` version -> https://pypi.org/project/gast/#history

**Comment by shinh** [comment]
@Rishav1 Thanks for your answer! Yeah, I realized the feature was incomplete, but I was wondering if it makes sense to merge this PR without implementing all necessary features (maybe with changing the title of the PR) since this PR is adding a lot of testcases which already look very useful. Sorry I didn't clarify this in the previous comment..

**Comment by Rishav1** [comment]
Sure. We can merge it. I changed the name.

**Comment by shinh** [comment]
Thanks!

**Pull request merged**
